
INSERT INTO type_entites (id, libele, description, created_at, updated_at) VALUES
(1, 'Direction', 'Direction', NOW(), NOW()),
(2, 'Bureau', 'Bureau', NOW(), NOW()),
(3, 'Service', 'Service', NOW(), NOW()),
(4, 'Division', 'Division', NOW(), NOW()),
(5, 'Poste', 'Poste', NOW(), NOW());

-- Insertion dans la table entites_organisation
INSERT INTO entites_organisation (id, libele, description, code, parent_id, type_entity_id, active, created_at, updated_at) VALUES
(1, 'DG', 'Directeur Général', 'Directeur Général', NULL, 1, true, NOW(), NOW()),
(2, 'SAC', 'Service audit et contrôle', 'Service audit et contrôle', NULL, 3, true, NOW(), NOW()),
(3, 'CAD', 'Cabinet du DG', 'Cabinet du DG', NULL, 2, true, NOW(), NOW()),
(4, 'REXP', 'Responsable exploitation', 'Responsable exploitation', NULL, 2, true, NOW(), NOW()),
(5, 'JDL', 'JG logement', 'JG logement', NULL, 2, true, NOW(), NOW()),
(6, 'PREVA', 'PREVA', 'PREVA', NULL, 2, true, NOW(), NOW()),
(7, 'JDO/HO3', 'JD Original/HO3', 'JD Original/HO3', NULL, 2, true, NOW(), NOW()),
(8, 'DD', 'Directeur Délégué', 'Directeur Délégué', NULL, 1, true, NOW(), NOW()),
(9, 'COM DIR/PIL', 'Comité de direction/pilotage', 'Comité de direction/pilotage', NULL, 2, true, NOW(), NOW()),
(10, 'SD', 'Secrétaire de direction', 'Secrétaire de direction', NULL, 2, true, NOW(), NOW()),
(11, 'ARCH', 'Archiviste', 'Archiviste', NULL, 5, true, NOW(), NOW()),
(12, 'SCE LABO', 'Service laboratoire', 'Service laboratoire', NULL, 3, true, NOW(), NOW()),
(13, 'SQHSE', 'Service QHSE', 'Service QHSE', NULL, 3, true, NOW(), NOW()),
(14, 'DAF', 'Division administrative et financière', 'Division administrative et financière', NULL, 4, true, NOW(), NOW()),
(15, 'SCE COMPT', 'Service comptable et fiscal', 'Service comptable et fiscal', NULL, 3, true, NOW(), NOW()),
(16, 'SCE RH', 'Service RH', 'Service RH', NULL, 3, true, NOW(), NOW()),
(17, 'SAA', 'Service Achat et Approvisionnement', 'Service Achat et Approvisionnement', NULL, 3, true, NOW(), NOW()),
(18, 'DCG', 'Division contrôle de gestion', 'Division contrôle de gestion', NULL, 4, true, NOW(), NOW()),
(19, 'Div Dis', 'Division distribution', 'Division distribution', NULL, 4, true, NOW(), NOW()),
(20, 'DSI', 'Division système infos', 'Division système infos', NULL, 4, true, NOW(), NOW()),
(22, 'DU', 'Division usine', 'Division usine', NULL, 4, true, NOW(), NOW());

-- Insertion dans la table plan_classement
INSERT INTO plan_classement (code_plan_classement, libelle_plan_classement, description_plan_classement, parent_id, numero_ordre) VALUES
('A000', 'ORGANISATION ET ADMINISTRATION', 'ORGANISATION ET ADMINISTRATION', NULL, 2),
('A100', 'Creation, evolution et mutation de l''entreprise', 'Creation, evolution et mutation de l''entreprise', 17, NULL),
('A110', 'Documents constitutifs de B&B SARL', 'Documents constitutifs de B&B SARL', 18, NULL),
('A120', 'Documents constitutifs de SCI FS2', 'Documents constitutifs de SCI FS2', 18, NULL),
('A130', 'Documents constitutifs de JD GOODS & SERVICES', 'Documents constitutifs de JD GOODS & SERVICES', 18, NULL),
('A140', 'Documents constitutifs de JD WINE & BEVERAGES', 'Documents constitutifs de JD WINE & BEVERAGES', 18, NULL),
('A150', 'Documents constitutifs de JD MANUFACTURING', 'Documents constitutifs de JD MANUFACTURING', 18, NULL),
('A160', 'Documents constitutifs de JD PACKAGING', 'Documents constitutifs de JD PACKAGING', 18, NULL),
('A200', 'Organisation, gouvernance et nomination', 'Organisation, gouvernance et nomination', 17, NULL),
('A210', 'Organigrammes de l''entreprise', 'Organigrammes de l''entreprise', 25, NULL),
('A220', 'Reglement interieur', 'Reglement interieur', 25, NULL),
('A230', 'Tenue des conseils d''administration et comite de gestion', 'Tenue des conseils d''administration et comite de gestion', 25, NULL),
('A240', 'Tenue des comites techniques et groupes de travail', 'Tenue des comites techniques et groupes de travail', 25, NULL),
('A250', 'Tenue des reunions de coordination des entites', 'Tenue des reunions de coordination des entites', 25, NULL),
('A260', 'Nomination des responsables et delegations de pouvoir ou procurations', 'Nomination des responsables et delegations de pouvoir ou procurations', 25, NULL),
('A300', 'Planification et strategies', 'Planification et strategies', 17, NULL),
('A310', 'Politiques internes et chartes diverses', 'Politiques internes et chartes diverses', 32, NULL),
('A320', 'Documents de strategies', 'Documents de strategies', 32, NULL),
('A330', 'Procedures diverses', 'Procedures diverses', 32, NULL),
('A340', 'Plans d''action et programmes d''activite periodiques', 'Plans d''action et programmes d''activite periodiques', 32, NULL),
('A400', 'Audit et controle de gestion', 'Audit et controle de gestion', 17, NULL),
('A410', 'Missions de conseil', 'Missions de conseil', 37, NULL),
('A420', 'Missions d''assurances', 'Missions d''assurances', 37, NULL),
('A430', 'Audits internes', 'Audits internes', 37, NULL),
('A440', 'Audits externes', 'Audits externes', 37, NULL),
('A450', 'Controle de la production', 'Controle de la production', 37, NULL),
('A460', 'Controle de caisse', 'Controle de caisse', 37, NULL),
('A470', 'Controle des travaux d''inventaire', 'Controle des travaux d''inventaire', 37, NULL),
('A480', 'Controle chiffre d''affaire', 'Controle chiffre d''affaire', 37, NULL),
('A500', 'Bilans', 'Bilans', 17, NULL),
('A510', 'Analyses et statistiques', 'Analyses et statistiques', 46, NULL),
('A520', 'Rapport d''activites et bilans', 'Rapport d''activites et bilans', 46, NULL),
('B000', 'RESSOURCES HUMAINES', 'RESSOURCES HUMAINES', NULL, 3),
('B100', 'Recrutement et gestion collective des carriers', 'Recrutement et gestion collective des carriers', 49, NULL),
('B110', 'Gestion previsionnelle des emplois et competences', 'Gestion previsionnelle des emplois et competences', 50, NULL),
('B120', 'Procedure d''embauche et gestion administrative d''embauche', 'Procedure d''embauche et gestion administrative d''embauche', 50, NULL),
('B130', 'Commission d''embauche', 'Commission d''embauche', 50, NULL),
('B140', 'Modalites integration employes', 'Modalites integration employes', 50, NULL),
('B150', 'DPR', 'DPR', 50, NULL),
('B160', 'Grille salariale et revision salariale', 'Grille salariale et revision salariale', 50, NULL),
('B170', 'Bilans-statistiques des emplois', 'Bilans-statistiques des emplois', 50, NULL),
('B200', 'Gestion individuelle des carriers et fichier du personnel', 'Gestion individuelle des carriers et fichier du personnel', 49, NULL),
('B210', 'Actes de gestion des carriers du personnel', 'Actes de gestion des carriers du personnel', 58, NULL),
('B220', 'Fichier du personnel employe', 'Fichier du personnel employe', 58, NULL),
('B230', 'Fichier du personnel temporaire et interimaire', 'Fichier du personnel temporaire et interimaire', 58, NULL),
('B240', 'Fichier stagiaires', 'Fichier stagiaires', 58, NULL),
('B250', 'Fichier des experts et consultants', 'Fichier des experts et consultants', 58, NULL),
('B300', 'Gestion des evaluations', 'Gestion des evaluations', 49, NULL),
('B310', 'Commission des evaluations', 'Commission des evaluations', 64, NULL),
('B320', 'Guide des evaluations', 'Guide des evaluations', 64, NULL),
('B330', 'Test et resultats des evaluations', 'Test et resultats des evaluations', 64, NULL),
('B340', 'Etat des absences', 'Etat des absences', 64, NULL),
('B350', 'Etat des sanctions', 'Etat des sanctions', 64, NULL),
('B400', 'Conditions de travail', 'Conditions de travail', 49, NULL),
('B410', 'Qualite, hygiene, sante et environnement au travail', 'Qualite, hygiene, sante et environnement au travail', 70, NULL),
('B420', 'Ethique', 'Ethique', 70, NULL),
('B430', 'Mesures disciplinaires', 'Mesures disciplinaires', 70, NULL),
('B440', 'Conflits de travail', 'Conflits de travail', 70, NULL),
('B500', 'Formation et perfectionnement', 'Formation et perfectionnement', 49, NULL),
('B510', 'Organisation des activites de formation en interne', 'Organisation des activites de formation en interne', 75, NULL),
('B520', 'Participation aux activites de formation en interne', 'Participation aux activites de formation en interne', 75, NULL),
('B530', 'Suivi et evaluation du personnel et des formations', 'Suivi et evaluation du personnel et des formations', 75, NULL),
('B600', 'Politique sociale au profit du personnel', 'Politique sociale au profit du personnel', 49, NULL),
('B610', 'Distinctions honorifiques', 'Distinctions honorifiques', 79, NULL),
('B620', 'Conges annuels', 'Conges annuels', 79, NULL),
('B630', 'Permissions d''absences', 'Permissions d''absences', 79, NULL),
('B640', 'Missions du personnel', 'Missions du personnel', 79, NULL),
('B650', 'Action sociale au profit du personnel, repas', 'Action sociale au profit du personnel, repas', 79, NULL),
('B660', 'Activites sportives, culturelles et loisirs', 'Activites sportives, culturelles et loisirs', 79, NULL),
('B670', 'Manifestations festives', 'Manifestations festives', 79, NULL),
('B700', 'Gestion des activites syndicales et associatives', 'Gestion des activites syndicales et associatives', 49, NULL),
('B710', 'Dialogue social (delegue du personnel)', 'Dialogue social (delegue du personnel)', 87, NULL),
('B720', 'Activites associatives', 'Activites associatives', 87, NULL),
('C000', 'INFORMATION, COMMUNICATION ET RELATIONS EXTERNES', 'INFORMATION, COMMUNICATION ET RELATIONS EXTERNES', NULL, 4),
('C100', 'Technologie de l''information et la communication', 'Technologie de l''information et la communication', 90, NULL),
('C110', 'Schema directeur informatiques et documentation technique', 'Schema directeur informatiques et documentation technique', 91, NULL),
('C120', 'Systemes d''information (logiciels, licences et abonnements etc.)', 'Systemes d''information (logiciels, licences et abonnements etc.)', 91, NULL),
('C130', 'Reseaux, protection et securite de l''information', 'Reseaux, protection et securite de l''information', 91, NULL),
('C140', 'Site web et portail d''entreprise', 'Site web et portail d''entreprise', 91, NULL),
('C150', 'Internet, intranet extranet et telecommunications', 'Internet, intranet extranet et telecommunications', 91, NULL),
('C160', 'Telephonie', 'Telephonie', 91, NULL),
('C200', 'Courrier et messagerie', 'Courrier et messagerie', 90, NULL),
('C210', 'Notes d''information', 'Notes d''information', 98, NULL),
('C220', 'Communique', 'Communique', 98, NULL),
('C230', 'Courrier entrant', 'Courrier entrant', 98, NULL),
('C240', 'Courrier sortant', 'Courrier sortant', 98, NULL),
('C250', 'Courrier interne', 'Courrier interne', 98, NULL),
('C260', 'Colis et messagerie', 'Colis et messagerie', 98, NULL),
('C300', 'Information documentaire', 'Information documentaire', 90, NULL),
('C310', 'Archives, systeme d''archivage physique et numerique', 'Archives, systeme d''archivage physique et numerique', 105, NULL),
('C320', 'Bibliotheque et documentation', 'Bibliotheque et documentation', 105, NULL),
('C340', 'Veille strategique et intelligence economique (business intelligence)', 'Veille strategique et intelligence economique (business intelligence)', 105, NULL),
('C400', 'Gestion de l''edition et des publications', 'Gestion de l''edition et des publications', 90, NULL),
('C410', 'Identification visuelle', 'Identification visuelle', 109, NULL),
('C420', 'Affichage', 'Affichage', 109, NULL),
('C430', 'Edition et publications', 'Edition et publications', 109, NULL),
('C500', 'Relations externes', 'Relations externes', 90, NULL),
('C510', 'Relations externes avec l''administration publique', 'Relations externes avec l''administration publique', 113, NULL),
('C520', 'Relations externes avec les entreprises publiques', 'Relations externes avec les entreprises publiques', 113, NULL),
('C530', 'Relations externes avec les entreprises privees', 'Relations externes avec les entreprises privees', 113, NULL),
('C540', 'Relations externes avec les institutions internationales', 'Relations externes avec les institutions internationales', 113, NULL),
('D000', 'PATRIMOINE MOBILIER ET IMMOBILIER', 'PATRIMOINE MOBILIER ET IMMOBILIER', NULL, 5),
('D100', 'Acquisition des biens meubles et immeubles', 'Acquisition des biens meubles et immeubles', 118, NULL),
('D110', 'Acquisition du materiel et mobilier', 'Acquisition du materiel et mobilier', 119, NULL),
('D120', 'Acquisition des equipements et materiel informatique', 'Acquisition des equipements et materiel informatique', 119, NULL),
('D130', 'Acquisition des automobiles', 'Acquisition des automobiles', 119, NULL),
('D140', 'Achat des biens immobiliers (terrains et batiments)', 'Achat des biens immobiliers (terrains et batiments)', 119, NULL),
('D150', 'Construction des batiments de bureaux', 'Construction des batiments de bureaux', 119, NULL),
('D160', 'Construction et amenagement des batiments et espaces commerciaux', 'Construction et amenagement des batiments et espaces commerciaux', 119, NULL),
('D170', 'Acquisition par adjudication', 'Acquisition par adjudication', 119, NULL),
('D200', 'Location', 'Location', 118, NULL);

-- Insertion dans la table metadata
INSERT INTO metadata (nom, libelle, question, type_champ, masque_saisie, longeur, concept_lie, domaine_valeur_lie, valeur_defaut, format_date, champ_incrementiel) VALUES
('Titre propre', 'Titre propre', 'Titre propre', 'text', 'Titre propre', 255, NULL, NULL, NULL, NULL, NULL),
('Titre parallèle', 'Titre parallèle', 'Titre parallèle', 'text', 'Titre parallèle', 255, NULL, NULL, NULL, NULL, NULL),
('Complément de titre', 'Complément de titre', 'Complément de titre', 'text', 'Complément de titre', 255, NULL, NULL, NULL, NULL, NULL),
('Auteur (s)', 'Auteur (s)', 'Auteur (s)', 'text', 'Auteur (s)', 255, NULL, NULL, NULL, NULL, NULL),
('Edition', 'Edition', 'Edition', 'text', 'Edition', 255, NULL, NULL, NULL, NULL, NULL),
('Lieu de publication (Ville)', 'Lieu de publication (Ville)', 'Lieu de publication (Ville)', 'text', 'Lieu de publication (Ville)', 255, NULL, NULL, NULL, NULL, NULL),
('Editeur', 'Editeur', 'Editeur', 'text', 'Editeur', 255, NULL, NULL, NULL, NULL, NULL),
('Date de publication (Année)', 'Date de publication (Année)', 'Date de publication (Année)', 'text', 'Date de publication (Année)', 255, NULL, NULL, NULL, NULL, NULL),
('Nombre de pages', 'Nombre de pages', 'Nombre de pages', 'text', 'Nombre de pages', 255, NULL, NULL, NULL, NULL, NULL),
('Dimensions', 'Dimensions', 'Dimensions', 'text', 'Dimensions', 255, NULL, NULL, NULL, NULL, NULL),
('Matériel d''accompagnement', 'Matériel d''accompagnement', 'Matériel d''accompagnement', 'text', 'Matériel d''accompagnement', 255, NULL, NULL, NULL, NULL, NULL),
('Collection', 'Collection', 'Collection', 'text', 'Collection', 255, NULL, NULL, NULL, NULL, NULL),
('ISSN', 'ISSN', 'ISSN', 'text', 'ISSN', 255, NULL, NULL, NULL, NULL, NULL),
('Notes', 'Notes', 'Notes', 'text', 'Notes', 255, NULL, NULL, NULL, NULL, NULL),
('ISBN', 'ISBN', 'ISBN', 'text', 'ISBN', 255, NULL, NULL, NULL, NULL, NULL),
('Nature du texte', 'Nature du texte', 'Nature du texte', 'text', 'Nature du texte', 255, NULL, NULL, NULL, NULL, NULL),
('Références', 'Références', 'Références', 'text', 'Références', 255, NULL, NULL, NULL, NULL, NULL),
('Objet', 'Objet', 'Objet', 'text', 'Objet', 255, NULL, NULL, NULL, NULL, NULL),
('Date de signature', 'Date de signature', 'Date de signature', 'text', 'Date de signature', 255, NULL, NULL, NULL, NULL, NULL),
('Fonction du signataire', 'Fonction du signataire', 'Fonction du signataire', 'text', 'Fonction du signataire', 255, NULL, NULL, NULL, NULL, NULL),
('Nom du signataire', 'Nom du signataire', 'Nom du signataire', 'text', 'Nom du signataire', 255, NULL, NULL, NULL, NULL, NULL),
('Intitulé', 'Intitulé', 'Intitulé', 'text', 'Intitulé', 255, NULL, NULL, NULL, NULL, NULL),
('Type d''opération', 'Type d''opération', 'Type d''opération', 'text', 'Type d''opération', 255, NULL, NULL, NULL, NULL, NULL),
('Numéro de la pièce', 'Numéro de la pièce', 'Numéro de la pièce', 'text', 'Numéro de la pièce', 255, NULL, NULL, NULL, NULL, NULL),
('Référence comptable', 'Référence comptable', 'Référence comptable', 'text', 'Référence comptable', 255, NULL, NULL, NULL, NULL, NULL),
('Code journal', 'Code journal', 'Code journal', 'text', 'Code journal', 255, NULL, NULL, NULL, NULL, NULL),
('Code comptable', 'Code comptable', 'Code comptable', 'text', 'Code comptable', 255, NULL, NULL, NULL, NULL, NULL),
('Date comptable', 'Date comptable', 'Date comptable', 'text', 'Date comptable', 255, NULL, NULL, NULL, NULL, NULL),
('Bénéficiaire', 'Bénéficiaire', 'Bénéficiaire', 'text', 'Bénéficiaire', 255, NULL, NULL, NULL, NULL, NULL),
('Numéro de compte', 'Numéro de compte', 'Numéro de compte', 'text', 'Numéro de compte', 255, NULL, NULL, NULL, NULL, NULL),
('Montant', 'Montant', 'Montant', 'text', 'Montant', 255, NULL, NULL, NULL, NULL, NULL),
('Code', 'Code', 'Code?', 'text', NULL, 60, NULL, NULL, NULL, NULL, NULL),
('Entité', 'Entité', 'quelle entité?', 'text', NULL, 60, NULL, NULL, NULL, NULL, NULL),
('Date', 'Date', 'Date?', 'text', NULL, 60, NULL, NULL, NULL, NULL, NULL),
('Version', 'Version', 'Version?', 'text', NULL, 60, NULL, NULL, NULL, NULL, NULL),
('Service', 'Service', 'Quel est le service', 'zone', NULL, 60, NULL, NULL, NULL, 'normal_date', NULL),
('Titre du document', 'Titre du document', 'quel est le titre du document?', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Année', 'Année', 'quel est l''année de production?', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('mois', 'mois', 'quel est le mois ?', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Poste', 'Poste', 'quel est le poste', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Titre du document', 'Titre du document', 'quel est le titre du document?', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('mois', 'mois', 'quel est le mois ?', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('l''entité', 'l''entité', 'quel entité?', 'text', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Portant', 'Portant', 'Note portant?', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Nom de la société', 'Nom de la société', 'quel est le nom de la société', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Nom', 'Nom', 'Nom', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Typologie', 'Typologie', 'Quel est le type de documents?', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Nature du document', 'Nature du document', 'Quel est la nature du document', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Projet', 'Projet', 'Quel est le nom du projet', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Client', 'Client', 'Quel est le nom du client', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Concepteur', 'Concepteur', 'Quel est le nom du concepteur', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Dessinateur', 'Dessinateur', 'Qui a réalisé le dessin', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Contrôleur', 'Contrôleur', 'Qui a contrôlé le dessin', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Maitre d''ouvrage', 'Maitre d''ouvrage', 'Qui réalise l''ouvrage', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Phase du projet', 'Phase du projet', 'Quelle est la phase du projet', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Site', 'Site', 'Ou est réalisé le projet', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Etudié par', 'Etudié par', 'Qui a réalisé l''éude', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Vérifier par', 'Vérifier par', 'Qui a effectué la vérification', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Numéro du projet', 'Numéro du projet', 'Quel est le numéro u projet', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL),
('Typlogie de l''image', 'Typologie', 'Quel est la typologie du document', 'zone', NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- Insertion dans la table groupes

-- Insertion dans la table groupes
INSERT INTO groupes (id,libele_groupe_utilisateur, type, description_groupe_utilisateur, created_at, updated_at) VALUES
('1','Administrateur Technique_B_B', 'TYPE_2', 'groupe pour les Administrateurs Technique', NOW(), NOW()),
('2','Administrateur Fonctionnelle_B_B', 'TYPE_1', 'groupe pour les Administrateurs Fonctionnelle', NOW(), NOW()),
('3','DCG', 'TYPE_0', 'DIVISION CONTROLE DE GESTION', NOW(), NOW()),
('4','DAA', 'TYPE_0', 'DIVISION ACHAT ET APPROVISIONNEMENT', NOW(), NOW()),
('5','DSI', 'TYPE_0', 'DIVISION DES SYSTEMES D''INFORMATION', NOW(), NOW()),
('6','DCA', 'TYPE_0', 'DIVISION CONTROLE ET AUDIT', NOW(), NOW()),
('7','DDR', 'TYPE_0', 'DIVISION DISTRIBUTION ET REDISTRIBUTION', NOW(), NOW()),
('8','DMC', 'TYPE_0', 'DIVISION MARKETNG ET COMMUNICATION', NOW(), NOW()),
('9','SQHSE', 'TYPE_0', 'SERVICE QUALITE, HYGIENE ET SECURITE DE L''ENVIRONEMENT', NOW(), NOW()),
('10','SCOMPTA', 'TYPE_0', 'SERVICE COMPTABILITE', NOW(), NOW()),
('11','SRH', 'TYPE_0', 'SERVICE DES RESSOURCES HUMAINES', NOW(), NOW()),
('12','ST', 'TYPE_0', 'SERVICE TECHNIQUE', NOW(), NOW()),
('13','DU', 'TYPE_0', 'DIVISION USINE', NOW(), NOW()),
('14','DG', 'TYPE_0', 'DG', NOW(), NOW()),
('15','DD', 'TYPE_0', 'DD', NOW(), NOW());

-- Insertion dans la table domaine_valeur
INSERT INTO domaine_valeur (id, libele, description, type) VALUES
(1, 'Actifs', 'Actifs', '1'),
(2, 'Etats des dossiers', 'Etats des dossiers', '2'),
(3, 'situation matrimoniale', 'situation matrimoniale', '0'),
(4, 'Support', 'Support', '0');

-- Insertion dans la table valeurs
INSERT INTO valeurs (libele, description, code, ordre, actif, domaine_valeur_id, created_at, updated_at) VALUES
('Dossiers', '1', '1', 1, true, 1, NOW(), NOW()),
('Documents', '1', '1', 1, true, 1, NOW(), NOW()),
('Mauvais', '0', '0', 2, true, 2, NOW(), NOW()),
('Bon', '0', '0', 2, true, 2, NOW(), NOW()),
('Mixte', '0', '0', 2, true, 2, NOW(), NOW()),
('Papier', '0', '0', 4, true, 4, NOW(), NOW()),
('Electronique', '0', '0', 4, true, 4, NOW(), NOW());

-- Insertion dans la table file_schemes

