spring:
  datasource:
    url: jdbc:postgresql://192.168.43.228:5432/harmony_db3
    username: gallagher
    password: gallagher09
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    validate-on-migrate: false
    baseline-on-migrate: true

  rabbitmq:
    host: 192.168.43.228
    port: 5672
    username: gallagher
    password: gallagher09
  
  mail:
    host: 192.168.43.228
    port: 1025
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        debug: true

logging:
  level:
    org.springframework.amqp: DEBUG
    org.springframework: DEBUG

server:
  port: 8200
  address: 0.0.0.0

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000 # 24 hours in milliseconds
  refreshExpiration: 604800000 # 7 days in milliseconds

# Configuration pour le service analytics BPMN
bpmn:
  analytics:
    service:
      url: http://localhost:5000
      timeout:
        connect: 10000 # 10 seconds
        read: 30000 # 30 seconds

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    filter:
      create: All tasks
    history-level: full
    authorization:
      enabled: false # Désactive la gestion fine des permissions pour utiliser directement les IDs métier
    job-execution:
      enabled: true
    database:
      schema-update: true
    metrics:
      enabled: false
    webapp:
      index-redirect-enabled: true
    generic-properties:
      properties:
        telemetry-reporter-activate: false
